### ISSUE TITLE
Implement overnight lending using Yield Tokens

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#1]
You can of course "roll" from one contract to another (say, ayBTC-(today) to ayBTC-(tomorrow)), but that sounds overly complicated.
Any simpler approach is possible?

**Comment by wallace21st** [comment]
constant maturity future, where the interest rate is reset daily? in that case, an index benchmark is required. In the fiat world, that would be libor

**Comment by fiftyeightandeight** [comment]
I suppose we can create something like OIS, but the question is how mechanically do we do that.
We can't do "dealer polling" (or can we?)
What does that also mean from the ayToken design perspective? Can this be implemented in a way consistent with the current design of ayToken? Or do we need to follow (as an entirely different design - not preferred) models like Compound/AAVE?

**Comment by fiftyeightandeight** [comment]
Think we can implement short-dated (even daily) ayToken that is auctioned every day (say in the first two hours of the creation) following #12.
The redeemed Token from the yesterday's ayToken can be rolled into today's ayToken by participating in the auction (i.e. sell Token, buy ayToken).

**Comment by fiftyeightandeight** [comment]
https://cointelegraph.com/news/crypto-needs-a-decentralized-daily-reference-rate/amp

The article talks about reference FX rates, but it will be very useful if we can, through the daily auction process, create an OIS standard for crypto.

**Comment by fiftyeightandeight** [comment]
duplicate of #90
