### ISSUE TITLE
DAO Implementation 

### ISSUE THREAD

**Issue by hyossid** [alexgo-io/alex-v1#101]
- fee-to-address should point to the relevant multisig contract at create-pool().
set-fee-rate-x(), set-fee-rate-y(), set-fee-to-address() and collect-fees() should check that contract-caller equals to fee-to-address.
- multisig contract should accept all valid pool tokens as votes. For example, for a multisig contract that owns a collateral rebalancing pool, both yield-token and key-token are valid votes.

**Comment by fiftyeightandeight** [comment]
@hyossid think we can close this?
