### ISSUE TITLE
Regtest bulk deploy scripts

### ISSUE THREAD

**Issue by JBotwina** [alexgo-io/alex-v1#104]

**Comment by hecool108** [comment]
In initialize-account.py, line 11, before 'mkdir', think we should have a judge if the folder exists. Or like I run it twice I will encounter:
```
Traceback (most recent call last):
  File "initialize-account.py", line 11, in <module>
    os.mkdir('../staged-contracts')
```

**Comment by hecool108** [comment]
Running initialize-nonce.py and got this
```
{
    "error": "transaction rejected",
    "reason": "NotEnoughFunds",
    "reason_data": {
        "actual": "0x00000000000000000000000000000000",
        "expected": "0x000000000000000000000000000007d0"
    },
    "txid": "5a858ddbc57e2ef6f057dd4ce20356feab0be6150594f6d33eab0b1d85971b0f"
}
```

**Comment by JBotwina** [comment]
@hecool108 
you don't have enough balance. you need to wait until you get stx. run python3 get-balance.py to check

**Comment by hecool108** [comment]
> @hecool108
> you don't have enough balance. you need to wait until you get stx. run python3 get-balance.py to check

I see, so can we give a friendly hint when I don't have enough balance? like when I run initialize-nonce.py, check the balance first and remind use with:
```
You don't have enough STX in your account, pls wait.
```

**Comment by JBotwina** [comment]
right, if balance == 0, then say wait. I like it. When I get a chance to look at it again, I'll add this. Meanwhile, lets close this.

**Comment by hecool108** [comment]
And also,(for lazybones like me) can we make these three parts together as an all-in-one tool?

1 Check and create necessary folders(remove the old files)
2 Run facet API and keep checking if the account received enough stx.
3 Deploy contract files and show the progress in the command line.

**Comment by JBotwina** [comment]
Yea, this is not a bad idea. We could constantly query the endpoint to see if the previous contract succeeded.
