### ISSUE TITLE
feat: flash-loan-user-margin.clar

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#105]
https://github.com/alexgo-io/alex-v1/commit/0e901258f02783963857aef96fe61c5b8851c40f

**Comment by fiftyeightandeight** [comment]
Please refer to https://github.com/alexgo-io/alex-v1/commit/8f1a52a27733d9a5aa11ebe311b3b955fdd87fa8

**Comment by hyossid** [comment]
my idea is trying to make single flash loan user contract,
