### ISSUE TITLE
Liquidity Bootstrapping Pool

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#12]
A simple, yet very useful, strategy that we can offer on ALEX - [Liquidity Bootstrapping Pool](https://coinmarketcap.com/alexandria/glossary/liquidity-bootstrapping-pool-lbp).

**Comment by fiftyeightandeight** [comment]
LBP could adopted to run auctions at each ayToken launch.
https://docs.balancer.fi/v/v1/smart-contracts/smart-pools/liquidity-bootstrapping-faq

**Comment by Rredlion** [comment]
reminds me of government bond auction or even syndication, where you have an auction book open signing up for interest before the actual price occurs

**Comment by fiftyeightandeight** [comment]
Indeed, except that everyone can participate!

**Comment by Rredlion** [comment]
Though not exactly the same, in the yield token paper, if it is physical settlement, they also propose the auction
