### ISSUE TITLE
Problems 2021-09-03

### ISSUE THREAD

**Issue by hecool108** [alexgo-io/alex-v1#131]
1. Please create the necessary pools after contract deployment. @JBotwina @fiftyeightandeight 
![Screen Shot 2021-09-03 at 1 46 32 PM](https://user-images.githubusercontent.com/5652583/131979797-854fd1fe-613f-4864-a6b0-f24a7bd0ac87.png)
2. The way of calculating APY based on maturity date is still not clear. Please help me to figure it out. @fiftyeightandeight 
3. get-ltv is still not on the function list. @hyossid @fiftyeightandeight 
4. How do I get block height from front-end? @MarvinJanssen 
5. How do I  translate block-height expire of yield token to time? @hyossid @fiftyeightandeight

**Comment by fiftyeightandeight** [comment]
2. `(/ (* (contract-call? .yield-token-pool get-yield yield-token) 52560) (expiry-block-height - now-block-height)` See (5). Assume 365 days have 52,560 blocks (i.e. 10mins per block).
3. Did you check [collateral-rebalancing-pool](https://explorer.stacks.co/txid/0x892399f12d34a2b29a0fbba6f1bbf941aa2c05365f7265deb5ca4396271e216f)? I see `get-itv` at line 181?
4. How about `network.getBlockTimeInfoUrl();` from [stacks.js](https://blockstack.github.io/stacks.js/modules/network.html)?
5. You need to calculate expiry in unix time.
```
(var-get now-block-height) ;; see (4), this will be in non-fixed point.
(var-get expiry-block-height) ;; this will be fixed point, so you need to transform it.
(var-get now-in-epoch) ;; so today in seconds.
(var-set now-to-expiry-in-epoch (* (- expiry-block-height current-block-height) u600))) ;; assume 10min per block-height
(var-set expiry-in-epoch (+ today-in-epoch now-to-expiry-in-epoch))
```

**Comment by fiftyeightandeight** [comment]
@hecool108 based on the above, I will close the issue. Please let me know if you have any further questions.
