### ISSUE TITLE
fix: regtest deployment scripts also should include pool creation to allow testing

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#132]
Let's agree to the exact details of the pools to be created. I have the following:

- CRP: (yield-usda-4380, wbtc)
- YTP: (yield-usda-4380, usda)
- FWP: (usda, wbtc)

@hecool108 @hyossid anything else we want (for testing)?

**Comment by JBotwina** [comment]
@fiftyeightandeight Ok so there will eventually be multiple different type of pools, not just one pool holding all the assets.

**Comment by fiftyeightandeight** [comment]
> @fiftyeightandeight Ok so there will eventually be multiple different type of pools, not just one pool holding all the assets.

Correct

**Comment by fiftyeightandeight** [comment]
@JBotwina we will also need to create `pool-token` contracts for the relevant pools.

**Comment by hyossid** [comment]
Pool Creating Script should be independent from deployment script. Notice that creating pool is just for easy testing purpose. 
For the testnet, We are going to use the following pool; 

CRP: (yield-usda-59760, wbtc)
YTP: (yield-usda-59760, usda)
FWP: (usda, wbtc)

where 59760 block height represents the 10-27-2021 12:00am HKT, a month after the testnet launch. 
relevant contracts are all deployed, so I think @JBotwina can work on creating an independent script which creates the relevant pool. 

Keep in mind that FWP should be created prior to CRP

**Comment by fiftyeightandeight** [comment]
We will need to create relevant token contracts. For example, pool-token-yield-usda-4380-usda.
@hyossid do you think you can create contracts, so @JBotwina can use them for pool creation?

**Comment by JBotwina** [comment]
I'll working on creating the contracts now. Will deploy in the following order:
1) FWP: (usda, wbtc)
2) CRP: (yield-usda-59760, wbtc)
3) YTP: (yield-usda-59760, usda)

**Comment by fiftyeightandeight** [comment]
@JBotwina we need to have/create the following contracts. Also, I would like @hecool108 to take the lead on creating testing environment set-up script. 

So to summarise, 

1. @JBotwina is responsible for deployment script. @hecool108 is responsible for test environment set-up script.
2. Contract developers are responsible for creating the required contracts for front-end testing.

### tokens
- wbtc
- usda

### yield-tokens
- yield-wbtc-59760
- yield-wbtc-79760

### key-tokens
- key-wbtc-59760-usda
- key-wbtc-79760-usda

### pool-tokens
- fwp-wbtc-usda
- ytp-yield-wbtc-59760-wbtc
- ytp-yield-wbtc-79760-wbtc

### FWP
- create-pool `wbtc` `usda` u50000000 u50000000 `fwp-wbtc-usda`

### CRP
- create-pool `wbtc` `usda` `yield-wbtc-59760` `key-wbtc-59760-usda`
- create-pool `wbtc` `usda` `yield-wbtc-79760` `key-wbtc-79760-usda`

### YTP
- create-pool `yield-wbtc-59760` `wbtc` `ytp-yield-wbtc-59760-wbtc`
- create-pool `yield-wbtc-79760` `wbtc` `ytp-yield-wbtc-79760-wbtc` 

@hecool108 I will incorporate the above into the UX/UI development plan. Please note we will need to create more contracts to test margin trading - let's do that after we are done with lend/borrow.

**Comment by hecool108** [comment]
I created a node app here, https://github.com/alexgo-io/alex-v1/tree/env-test/init-js-tool
It can:
1 update oracle price via CoinGecko API (tested)
2 create FWP/CRP/YTP pool. (tested)

https://www.loom.com/share/ca8790978cbf40d08f8ee91363cc7447?from_recorder=1&focus_title=1

Still missing contracts:

yield-wbtc-79760
key-wbtc-79760-usda
ytp-yield-wbtc-79760-wbtc

**Comment by JBotwina** [comment]
@hecool108 I think we are not going to use the 79760s for regtest.

**Comment by fiftyeightandeight** [comment]
@JBotwina we also need to create the following `multisig`:

- multisig-fwp-wbtc-usda-50-50
- multisig-crp-wbtc-usda-59760
- multisig-crp-wbtc-usda-79760
- multisig-ytp-yield-wbtc-59760-wbtc
- multisig-ytp-yield-wbtc-79760-wbtc

**Comment by JBotwina** [comment]
https://www.loom.com/share/a19b57dd0964427bb8d19a09dd007636
