### ISSUE TITLE
fix: tracking of dev from main 

### ISSUE THREAD

**Issue by hyossid** [alexgo-io/alex-v1#148]
dev should follow main.
- pool token naming change
- oracle owner to tx-sender
- 59760 token addition

**Comment by JBotwina** [comment]
@hyossid I am assuming this issue tracks the changes we needed to make to main, but didnt go through dev first? So they are not present in dev?

**Comment by fiftyeightandeight** [comment]
Also include the fix #142. I tried to cherry-pick as many as possible in #157, but might have missed a few things.

**Comment by hyossid** [comment]
done
