### ISSUE TITLE
fix: CRP, get-ltv error, CostBalanceExceeded

### ISSUE THREAD

**Issue by hecool108** [alexgo-io/alex-v1#154]
Call CRP function get-ltv, with paramters, 

token-wbtc token-usda u5976000000000

got error:
Error: Unchecked(CostBalanceExceeded(ExecutionCost { write_length: 0, write_count: 0, read_length: 81027, read_count: 33, runtime: 96424000 }, ExecutionCost { write_length: 0, write_count: 0, read_length: 100000, read_count: 30, runtime: 1000000000 }))

**Comment by fiftyeightandeight** [comment]
@hecool108 just to confirm, this error was thrown when you made an API call at Hiro regtest?

**Comment by hecool108** [comment]
> @hecool108 just to confirm, this error was thrown when you made an API call at Hiro regtest?
> 
> Can you let me know the relevant code, so I can reproduce?

I made a stack.js call, with stacks.js package "@stacks/transactions" callReadOnlyFunction. the read-only function should be called without fee, so it's no need to call the wallet function.

the parameters are:

```json
{
    "contractAddress": "ST1RKT6V51K1G3DXWZC22NX6PFM6GBZ8FQKSGSNFY",
    "contractName": "collateral-rebalancing-pool",
    "functionName": "get-ltv",
    "functionArgs": [
        {
            "type": 6,
            "address": {
                "type": 0,
                "version": 26,
                "hash160": "713d1b650cc301b7bcfb042af4d67d0d05fd0fbc"
            },
            "contractName": {
                "type": 2,
                "content": "token-wbtc",
                "lengthPrefixBytes": 1,
                "maxLengthBytes": 128
            }
        },
        {
            "type": 6,
            "address": {
                "type": 0,
                "version": 26,
                "hash160": "713d1b650cc301b7bcfb042af4d67d0d05fd0fbc"
            },
            "contractName": {
                "type": 2,
                "content": "token-usda",
                "lengthPrefixBytes": 1,
                "maxLengthBytes": 128
            }
        },
        {
            "type": 1,
            "value": "56f655b7000"
        }
    ],
    "network": {
        "version": 128,
        "chainId": 2147483648,
        "bnsLookupUrl": "https://stacks-node-api.mainnet.stacks.co",
        "broadcastEndpoint": "/v2/transactions",
        "transferFeeEstimateEndpoint": "/v2/fees/transfer",
        "accountEndpoint": "/v2/accounts",
        "contractAbiEndpoint": "/v2/contracts/interface",
        "readOnlyFunctionCallEndpoint": "/v2/contracts/call-read",
        "_coreApiUrl": "https://stacks-node-api.regtest.stacks.co"
    },
    "senderAddress": "ST1RKT6V51K1G3DXWZC22NX6PFM6GBZ8FQKSGSNFY"
}
```

**Comment by fiftyeightandeight** [comment]
This error most likely due to `get-ltv` not optimised (i.e. too expensive). Let's use mock data for now until it is optimized.
For reference, see [Discord](https://discord.com/channels/621759717756370964/691807526118883418/885028429777485834).

**Comment by fiftyeightandeight** [comment]
deployment-v4 fixes this.
