### ISSUE TITLE
Extend Balancer Weighted Pool to incorporate concentrated liquidity

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#17]
### Constant weights
https://docs.alexgo.io/platform-architecture-that-supports-ecosystem-development#weighted-equation

### Dynamic weights
https://docs.alexgo.io/platform-architecture-that-supports-ecosystem-development#collateral-rebalancing-equation
https://docs.alexgo.io/platform-architecture-that-supports-ecosystem-development#liquidity-bootstrapping-equation

**Comment by jingstat** [comment]
https://colab.research.google.com/drive/1y3f1bAGboAQu2rDe_eGfMWoGERmoTYDS?usp=sharing#scrollTo=GHpWQyqaf2lp
