### ISSUE TITLE
fix(multisig): clean up required across trait and implementation

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#172]
- [ ] remove `fee-collector`
- [ ] `multisig` contract must implement `trait-multisig-vote`

See clarity/contracts/multisig/multisig-ytp-yield-wbtc-59760-wbtc.clar

**Comment by hyossid** [comment]
think I should have done this..... but seems done right?

**Comment by fiftyeightandeight** [comment]
Yes, essentially this is a duplicate of #180
