### ISSUE TITLE
fix(multisig): fixed-point vs. non fixed-point

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#179]
we need to review all the multisig contracts and make sure we don't mix up fixed point and non-fixed point
at the moment, there are many places where they are mixed up.
my suggestion is, for multisig only, we assume everything is in non-fixed point and use the native arithmetic operators, while converting all those fixed point values into non-fixed point.

**Comment by hyossid** [comment]
I'm fixing this, will be reflected on fwp testcases update

**Comment by hyossid** [comment]
Trivial Issues :  
- What if someone calls token contract and call mint function to his own account for now ?  
- Don't we need any interfaces for retrieving collected fee from multisig ?

**Comment by fiftyeightandeight** [comment]
*    we need (hard coded or not) authorisation on mint/burn. For example, only contract calls via yield-token-pool can mint/burn yield-tokens.
  *   Yes

________________________________
