### ISSUE TITLE
fix: error code standardization -2 

### ISSUE THREAD

**Issue by hyossid** [alexgo-io/alex-v1#185]
Due to many changes, error code needs to be arranged again. 
Frontend can only rely on errorcode when they face with errors.

**Comment by JBotwina** [comment]
@hyossid 

I think it would be best to follow this example
(define-constant not-authorized-err u1000)

This way, when we return an err, the err keyword is explicit:
(err not-authorized-err)

**Comment by fiftyeightandeight** [comment]
@MarvinJanssen your thoughts on the error code style? Think we should agree to something.

**Comment by fiftyeightandeight** [comment]
As discussed with @JBotwina yesterday. Just to be clear, we don't want to spend too much time here, so let's be as efficient as possible.

In terms of what we should do.
1. we need to agree to the error code style. "err" at the beginning? at the end? all big capital letters?
2. group them to categories (like "General Error", "Pool Error", etc.)
3. remove redundant errors.
4. re-word, where needed, errors so they make more sense.
5. update the doc.

**Comment by JBotwina** [comment]
Yes, Sidney and I agreed that we should define the errors like this:
(define-constant NOT-AUTHORIZED-ERR u1000)

He has already cleaned up and deleted the useless error code on the fix/errcode branch. I will make the other changes today.

**Comment by hyossid** [comment]
done and merged
