### ISSUE TITLE
[DEV] Vault Implementation

### ISSUE THREAD

**Issue by hyossid** [alexgo-io/alex-v1#21]
Vault implementation using trait-vault

1. alex-vault
  - [x] get-balance
  - [x] get-balances
  - [x] transfer-to-vault
  - [x] transfer-from-vault
  - [x] flash-loan

**Comment by fiftyeightandeight** [comment]
@hyossid where are we on this please?

**Comment by hyossid** [comment]
- [ ] Implement a transfer function on vault, which can transfer and set on vault balance list

**Comment by hyossid** [comment]
1. get-balance in vault should return the 'sum' value of all token
2. remove hardcoded codes

**Comment by fiftyeightandeight** [comment]
@hyossid @hecool108 I cleaned up / simplified the vault implementation. 

- `flash-loan` supports a **fixed** list of tokens to be borrowed (three). Think we should handle borrowing < 3 at the client side.
- removed `get-balances`. Contract's inability to list out tokens it holds led to the map, etc., but this over-complicates the codes without clear benefits. We retain `get-balance` so if a `flash-loan-user` wants to check vault-held balance of a token before executing a flash loan operation, he/she can iterate at the client side.
- removed `transfer-to-vault` and `transfer-from-vault`. With the removal of internal map, I don't see any needs for these. So reverting to calling `transfer` from token.
