### ISSUE TITLE
ayToken / Collateral Equation

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#3]
Can we extend the AMM logic to implement collateralised lending?
Post collateral to mint ayToken == sell collateral to buy ayToken?

**Comment by wallace21st** [comment]
What collateral do you refer to here? In the doc, collateral is STX, whereas ayToken is Bitcoin. Does your collateral refer to any other coin(s) other than STX?

**Comment by fiftyeightandeight** [comment]
If we say we will start with three base tokens (BTC, STX and USD), we have the following pairs:

1. ayBTC-{maturity} / STX
2. ayBTC-{maturity} / USD
3. ayUSD-{maturity} / STX
4. ayUSD-{maturity} / BTC
5. aySTX-{maturity} / BTC
6. aySTX-{maturity} / USD

(5)/(6) will allow non-STX holders to establish levered long positions on STX.
(2)/(4) will allow BTC holders to hedge (2) or lever on upside (by selling USD and buying BTC -(4)).
(1)/(3) will be interesting to STX holders (and potentially unlock value from STX locked for stacking).

**Comment by fiftyeightandeight** [comment]
ayToken / Collateral Equation will implement a dynamic delta trading strategy. 
For example, ayBTC / USD pool (i.e. borrow BTC against USD) will implement a dynamic hedging strategy against BTC upside (i.e. sell USD and buy BTC as BTC spot goes up, and vice versa). The resulting rebalancing between USD and BTC will be then executed by arbitrageurs participating in the pool pricing curve. See some illustration [here](https://docs.google.com/spreadsheets/d/1d_Pzl0hoRFsD5q3yl97OxHmo_pVBf9tIgTAG4dfzENo?authuser=alexd%40alexgo.io&usp=drive_fs).
The borrower effectively is an LP (and receives ayBTC as the PoolToken) and the USD collateral provided will be automatically converted into a basket of USD and BTC.

- The main benefit is that we can be (much) more aggressive in LTV and potentially remove liquidation entirely (with appropriate LTV and reserve fund). This also allows aggregation of all ayToken into a single pool (rather than separate pool for each borrower).
- The main drawback is that the collateral received at the time of repayment will not be same in USD value as the original value (due to rebalancing).

**Comment by fiftyeightandeight** [comment]
[WeightedMath](https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/WeightedMath.sol) with new weights re-calculated at each block?

**Comment by jingstat** [comment]
I think the dynamic rebalance on the collateral makes sense.  In the illustration, I only see one side of the story: the collateral values always went down.  I wonder what if the borrowed values went down, even though there if no liquidation stress, will the 50-50 pool (borrowed and collaterals) be reblanced toward the collaterals (to maintain the total collateral values)?

**Comment by fiftyeightandeight** [comment]
Yes, you can see the impact of borrowed value going down by setting BTCUSD growth at, say, -50%. In that case, the pool will gradually rebalance out of BTC (borrowed) and into USD (collateral).
________________________________

**Comment by Rredlion** [comment]
This certainly looks interesting. Next is perhaps to test the idea in a real example, esp around volatile time.

**Comment by fiftyeightandeight** [comment]
Exactly. The delta hedge depends on the vol input, so we need to stress test across LTV and BS vol to find the right balance.
@jingstat LTV and BS vol are two of the params (in addition to some others we may need) that an Authorizer of the pool can set.
