### ISSUE TITLE
[DOC] Developer Documentation - API

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#31]
- [x] Fixed Weight Pool
- [x] Collateral Rebalancing Pool
- [x] Weighted Equations
- [x] Vault

**Comment by hyossid** [comment]
For the Function Highlighting part, I have misunderstood that it wasn't possible to put markdown file at gitbook.

Stacks official documentation is based on mdx and next.js
https://github.com/mdx-js/mdx
https://nextjs.org/
