### ISSUE TITLE
refactor(pools): Remove unnecessary check 

### ISSUE THREAD

**Issue by LNow** [alexgo-io/alex-v1#312]
https://github.com/alexgo-io/alex-v1/blob/42ced44233ce948213de00c7ee45c9e53d18b4c0/clarity/contracts/pool/fixed-weight-pool.clar#L207-L216

should be replaced with:
```clojure
(asserts! 
  (and 
    (map-insert pools-map { pool-id: pool-id } { token-x: token-x, token-y: token-y, weight-x: weight-x, weight-y: weight-y }) 
    (map-insert pools-data-map { token-x: token-x, token-y: token-y, weight-x: weight-x, weight-y: weight-y } pool-data)
  )
  ERR-POOL-ALREADY-EXISTS 
)   
```

Reasoning: `map-insert` will fail if item already exists in a map, therefore it can replace `map-get + map-set`

**Comment by fiftyeightandeight** [comment]
Hi @LNow , thank you for your comment. `map-insert` is indeed neat. In the above case, however, the proposal (with `map-insert`) would allow creation of, for example, WBTC-USDA pair (i.e. `token-x` = WBTC, `token-y` = USDA), even when we already have USDA-WBTC pair (i.e. `token-x` = USDA, `token-y` = WBTC)?
Line 209-210 ensures this does not happen. What's your thoughts?

**Comment by LNow** [comment]
@fiftyeightandeight you are right. I forgot that you don't want to have 2 registered pairs (X-Y and Y-X) but only one (X-Y or Y-X).

**Comment by fiftyeightandeight** [comment]
Great, I will close the issue then. Thank you!
