### ISSUE TITLE
feat: add uSTX lending/borrowing

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#323]

**Comment by SaadTahirTintash** [comment]
I need some information regarding this feature. I've got two implementations in mind.

I can use the following approach and create a `wrapper-stx-token` which will work the same as `token-wbtc`. However I need to know if you have the service where if the user `mints wstx`, the service will handle the transfer of `stx` from the user into the contract and then `wstx` is minted.
```
(define-public (mint (recipient principal) (amount uint))
  (begin
    (asserts! (is-eq tx-sender (var-get contract-owner)) ERR-NOT-AUTHORIZED)
    (ft-mint? wstx (fixed-to-decimals amount) recipient)
  )
)
```

However, if we don't have such service then I will have to add the logic inside the contract where `stx-transfer?` is called from the tx-sender and if the transaction is successful, the `wstx` is minted in his account.
```
(define-public (mint (recipient principal) (amount uint))
  (begin
    (asserts! (is-eq tx-sender recipient) ERR-NOT-AUTHORIZED)
    (try! (stx-transfer? amount tx-sender (as-contract tx-sender)))
    (ft-mint? ustx (fixed-to-decimals amount) tx-sender)
  )
)
```

**Comment by fiftyeightandeight** [comment]
Hi @SaadTahirTintash , we don't have a service to handle `stx-transfer`, so the second option makes sense, except that `stx` should be sent to `alex-vault`.

```
(define-public (mint (recipient principal) (amount uint))
  (begin
    (asserts! (is-eq tx-sender recipient) ERR-NOT-AUTHORIZED)
    (try! (stx-transfer? amount tx-sender .alex-vault))
    (ft-mint? ustx (fixed-to-decimals amount) tx-sender)
  )
)
```

When a user burns `wstx`, `stx` should also be sent from `alex-vault` (since `wrapper-stx-token` does not hold any `stx`). This will require adding `transfer-stx` to `alex-vault` that checks if `contract-caller` is approved and, if it is, transfers the requested `stx` to `recipient`, similar to `transfer-ft` (below)

https://github.com/alexgo-io/alex-v1/blob/ed7f3d83e5d8662fa902f43f2b58dcba9a6430e9/clarity/contracts/alex-vault.clar#L60-L67

**Comment by SaadTahirTintash** [comment]
Yeah that makes total sense now. One more thing that in order to test `wstx`, I cannot use `faucet` contract to `get-some-tokens` because the check for `contract-owner` conflicts with the `wstx` mint. So do we have some test cases for `token` transfers, mints, burns or should I write separate for `wstx` in the `faucet` contract.
