### ISSUE TITLE
fix: remove minting of tokens for testing purposes

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#324]
https://github.com/alexgo-io/alex-v1/blob/42ced44233ce948213de00c7ee45c9e53d18b4c0/clarity/contracts/token/token-alex.clar#L99

These should be handled at the relevant test case, rather than at a contract level (which then affects every test case that uses the contract)

**Comment by hyossid** [comment]
working on feat/minttokenfix branch

**Comment by fiftyeightandeight** [comment]
@SaadTahirTintash , would you please help look into this. Please commit the changes to #349 .
Hard-coded minting of tokens for testing purposes needs to be replaced with test model (https://github.com/alexgo-io/alex-v1/blob/feat/semi-fungible-token/clarity/tests/models/alex-tests-tokens.ts)

**Comment by SaadTahirTintash** [comment]
There are already some commits in this branch of removing the minting. Should I take rewrite them in #349 and commit?
