### ISSUE TITLE
fix: change decimals of `wbtc` and `usda`

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#330]
Refer to https://github.com/alexgo-io/alex-v1-app/issues/237.
closes #313

**Comment by SaadTahirTintash** [comment]
I've pushed the commits for the test cases of YTP, FWP and CRP for you to review the numbers.

**Comment by fiftyeightandeight** [comment]
Hi @SaadTahir28 , I reviewed the numbers over the weekend, and am coming to  conclusion that it is actually very hard to support zero decimals, primarily due to that we use 8-digit fixed notation for most of the calculation and, either the decimals get truncated (not something we want) or extra care needs to be given to properly handle this (not something I think that is worth pursuing).

I will ask you to help me on https://github.com/alexgo-io/alex-v1/pull/349 instead.

**Comment by SaadTahirTintash** [comment]
Yeah exactly. I was also having these issues and thought of that it is certainly not possible because of decimal places. I will start looking into this issue today and understand what is going on.
