### ISSUE TITLE
feat: CRP with `yield-token` as collateral

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#333]
Current CRP support `ft-trait` as token and `ft-trait` as collateral. Because of this, it cannot support `yield-token` as collateral.
We may create a new CRP that support `ft-trait` as token and `yield-token-trait` as collateral.

**Comment by hyossid** [comment]
I see, then to create 2 CRP right?

**Comment by fiftyeightandeight** [comment]
> I see, then to create 2 CRP right?

Yes, say, `yield-collateral-rebalancing-pool.clar`?

**Comment by hyossid** [comment]
Ok Ill create and request for review
