### ISSUE TITLE
doc: update of error codes and source code documentation

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#351]

**Comment by fiftyeightandeight** [comment]
### Error Codes

- [ ] Ensure every error code is defined as "ERR-<BRIEF DESCRIPTION>"
- [ ] Remove unnecessary/unused error codes from contracts
- [ ] Update the Gitbook

### Source Code Documentation

Source code comments should follow the following syntax:
```
;; @desc <description of the contract/function>
;; @restricted <describe here is the contract/function use is restricted to certain owners>
;; @param <name>; <description of parameter>
;; @returns <return type> (e.g. (response bool uint))
;; @post <describe post condition>
```

- [ ] Update/add the source code comments

**Comment by fiftyeightandeight** [comment]
Hi @SaadTahirTintash , in between your assignments, can you please follow up on this. Thank you.

**Comment by SaadTahirTintash** [comment]
Do you need me to verify that all the Error Codes are present in the code? The error code `ERR-STX-TRANSFER-FAILED` was added by me when adding `token-wstx`. It has a wrong error code of `err u3001` for now.

**Comment by fiftyeightandeight** [comment]
> Do you need me to verify that all the Error Codes are present in the code? The error code `ERR-STX-TRANSFER-FAILED` was added by me when adding `token-wstx`. It has a wrong error code of `err u3001` for now. It should be `err u9003` according to Gitbook

Yes, please.

**Comment by SaadTahirTintash** [comment]
I've created a change request on Gitbook with some comments. I've cross checked all the errors in the contracts and refactored them as well. The code is pushed to #349 branch

**Comment by fiftyeightandeight** [comment]
Hi @SaadTahirTintash I merged your changes to Gitbook. Please continue working on the rest of the issue.
Thank you.

**Comment by SaadTahirTintash** [comment]
` Remove unnecessary/unused error codes from contracts ` Do you need me to do this as well? I haven't checked it out thoroughly yet.

**Comment by fiftyeightandeight** [comment]
Yes, please. I want you to follow up with everything on the checklist.

**Comment by SaadTahirTintash** [comment]
`Remove unnecessary/unused error codes from contracts` is fixed now

**Comment by naila24** [comment]
Pull request for source code documentation is create and can be found [here](https://github.com/alexgo-io/alex-v1/pull/377)

**Comment by naila24** [comment]
Pull request for duplicate error codes removal can be found [here](https://github.com/alexgo-io/alex-v1/pull/397)
