### ISSUE TITLE
fix: clean-up / removal of unused fixed-point functions from contracts

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#354]

**Comment by SaadTahirTintash** [comment]
Can you explain about this issue? I see `math-fixed-point` comments in the contracts but no `fixed-point` functions.

**Comment by fiftyeightandeight** [comment]
`collateral-rebalancing-pool` contract, for example, has more than 300 lines of code relating to fixed-point functions:

https://github.com/alexgo-io/alex-v1/blob/bed01611043fed61c2f2515a427c11a417d57356/clarity/contracts/pool/collateral-rebalancing-pool.clar#L983-L1309

And you will see similar lines of code at other contracts too.

It could be the case that all these lines are required by the contract, but, if it does not, those unused codes should be removed.

**Comment by SaadTahirTintash** [comment]
`math-fixed-point.clar` and `math-log-exp.clar` are two files that are doing the same thing which every other file is doing. Should I refactor the `contract-call?` to this contract?

**Comment by fiftyeightandeight** [comment]
No, the functions in those contracts were intentionally moved to other contracts to reduce the runtime cost.
They should stay where they are.
