### ISSUE TITLE
fix: `map`/`fold` with trait reference passed

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#356]
When you want to iterate through a function, we typically use `map` or `fold`. 
If such a function requires more than one parameter (other than the value to iterate over), then we can use, for example, `fold` with a custom function that returns a tuple that includes those required parameters (for example: https://github.com/alexgo-io/alex-v1/blob/a25cb84049296a540e30f722c3f58f42559a300e/clarity/contracts/pool/stacking-pool.clar#L63-L68).

But what if one of such parameters is a trait reference?

https://github.com/alexgo-io/alex-v1/blob/a25cb84049296a540e30f722c3f58f42559a300e/clarity/contracts/pool/stacking-pool.clar#L195-L197

**Comment by noumanahmads** [comment]
`map` can take multiple sequences, i think what we can do here is that 

`(map claim-stacking-reward reward-cycles (list poxl-token-trait poxl-token-trait ... ))`

`reward-cycles` length is` 32`, list of traits should also be `32`
