### ISSUE TITLE
Real-time margined loans with minimal counterparty risk

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#4]
Stablecoins are typically implemented as an overcollateralised loan (say 50% LTV) with a liquidation trigger (say 66% Max LTV).
No periodic margining is implemented (as far as I know), which could be expensive to implement on ETH.
On Stacks, with faster transaction speed and lower transaction fee, can we implement a real-time margined loans with minimal counterparty risk?

**Comment by wallace21st** [comment]
In fiat world, where collaterals are generally bond, this is related to the quality of the collateral. Haircut will be applied to the collateral. Haircut is predetermined in CSA. This is similar to our case of deciding liquidation level before the trade. 

If a variate liquidation level needs to be applied, I suppose it will be related to the underlying risk profile of the digital currency, such as its volatility and its past performance during stress period, such as Mar 2020. 

We can also check how other platforms deal with stress scenario, i.e whether the margin requirement is adjusted or not.

**Comment by fiftyeightandeight** [comment]
In our case, collateral is fixed, so is the haircut. 
If we think about CSA, even daily zero threshold margining has settlement risk (you have call margin, the counterparty needs to agree, they then need to transfer that amount, etc.), followed by a cure period (typically 2 weeks), which adds to more counterparty risk.
But daily margining still helps a lot and goes a long way in reducing the counterparty risk.
So, in our collateralised lending, what if we make that margin call real-time (based on a threshold) and automatically debit (or credit) additional (excess) margin from (to) the borrower address (all of which is written in the smart contract)? 
And what if we trigger automatic liquidation if the balance at the borrower address does not meet that additional margin call?
What haircut in that case can we apply, vs. the current typical collateralised lending?

**Comment by wallace21st** [comment]
Think we can do whatever we like. What you propose is similar to what banks do nowadays.

One of the risk I can think about is that: if it is variation margin, I.e., it is always set to be a constant to the collateral and there is daily margin call, traders might not be willing to trade with you if other platforms are charging a fixed number. Think there is a fine balance in between these two approaches

**Comment by wallace21st** [comment]
Might be something like higher fixed margin, say 150% to start with; and 140% for selecting variation margin, but it always needs to be kept as a constant of 140%? At the end of day, it is a balance between liquidity and proper risk management.

**Comment by fiftyeightandeight** [comment]
Think we can think about the specific numbers (fixed margin vs. variation margin) at a later stage, but I agree with you to the core idea – it’s essentially a threshold-based variation margined loan, whose haircut is determined based on the risk assessment of that particular pair.

From: wallace21st ***@***.***>
Date: Monday, 14 June 2021 at 10:03 PM
To: alexgo-io/alex-v1 ***@***.***>
Cc: fiftyeightandeight ***@***.***>, Author ***@***.***>
Subject: Re: [alexgo-io/alex-v1] Real-time margined loans with minimal counterparty risk (#4)

Might be something like higher fixed margin, say 150% to start with; and 140% for selecting variation margin, but it always needs to be kept as a constant of 140%? At the end of day, it is a balance between liquidity and proper risk management.

**Comment by fiftyeightandeight** [comment]
Duplicate of #3.
This feature has been incorporated into lending pool design.
