### ISSUE TITLE
ALEX banana info page typo

### ISSUE THREAD

**Issue by 314159265359879** [alexgo-io/alex-v1#489]
There instead of Their
at: https://app.alexlab.co/launchpad/4op2et5VyvMgJA2Aq94M4q/details

![image](https://user-images.githubusercontent.com/33360391/156931149-bbfff575-9a21-4fbb-9b1b-75fec28adfec.png)

From: https://discord.com/channels/856358412303990794/856358412303990797/950036032210997298

**Comment by fiftyeightandeight** [comment]
Fixed - thank you.
