### ISSUE TITLE
Missing `proposal-trait.clar` file

### ISSUE THREAD

**Issue by LNow** [alexgo-io/alex-v1#528]
Due to missing `proposal-trait.clar` file it is impossible to run test suite.

On top of that CI is producing false positive results: https://github.com/alexgo-io/alex-v1/runs/5458993192?check_suite_focus=true

**Comment by fiftyeightandeight** [comment]
Hi @LNow , we use a custom dependency management tool, please run the following and try running test suites again.

```
> cd <project root>/clarity
> sh ./scripts/clarinet_manager.sh update alex_dao main
> sh ./scripts/clarinet_manager.sh install alex_dao
```

The list of dependencies (not all are required) is available here: https://github.com/alexgo-io/alex-v1/blob/main/clarity/Clarinet.json

@caoer , fyi

**Comment by LNow** [comment]
Hey @fiftyeightandeight !
It doesn't work anyway.
https://github.com/alexgo-io/alex-dao-proposals is not accessible - I bet it is a private repository.

**Comment by fiftyeightandeight** [comment]
Yes, https://github.com/alexgo-io/alex-dao-proposals is a private repo. Have you tried with this private repo removed from https://github.com/alexgo-io/alex-v1/blob/main/clarity/Clarinet.json? That should work.

**Comment by LNow** [comment]
Without `alex-dao-proposals` it works as it should.
