### ISSUE TITLE
Pool specification

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#6]
Please refer to IPool of [Class Diagram](https://docs.alexgo.io/class-diagram)

**Comment by jingstat** [comment]
High level: 

![pool_diagram_highlevel](https://user-images.githubusercontent.com/19434767/122811715-d24f2500-d29e-11eb-815d-c369db55193b.jpeg)


![Pool_diagram (1)](https://user-images.githubusercontent.com/19434767/122811714-d24f2500-d29e-11eb-8b38-eba201bcb829.jpeg)

**Comment by fiftyeightandeight** [comment]
The bare-bone specification here:
![](https://yuml.me/alexgo/alex-v1-class.svg)
