### ISSUE TITLE
[DEV] Floating point multiplication bug

### ISSUE THREAD

**Issue by hyossid** [alexgo-io/alex-v1#65]
Because we set the default unit as 100000000, multiplication of floating point comes to an issue. 

Since clarity uses 128 bit unsigned integer, we are allowed only to store 10^16. 

So we need to change our multiplication function on math library.

**Comment by fiftyeightandeight** [comment]
Can you please elaborate again the exact problem you see? 128-bit unsigned can store up to 2^128 (> 10^16)?
