### ISSUE TITLE
feat: create dummy USDC and WBTC with price manually updated using oracle

### ISSUE THREAD

**Issue by fiftyeightandeight** [alexgo-io/alex-v1#77]

**Comment by fiftyeightandeight** [comment]
@hecool108 can we build a bot that fetches prices and update `open-oracle`?

Example API: https://github.com/miscavage/CoinGecko-API
`open-oracle`: https://github.com/alexgo-io/alex-v1/blob/main/clarity/contracts/open-oracle.clar

**Comment by hecool108** [comment]
Yep, Let me integrate a function inside our SDK to call oracle.

**Comment by fiftyeightandeight** [comment]
@hecool108 @hyossid can we please have you two to own this?

**Comment by hecool108** [comment]
> @hecool108 @hyossid can we please have you two to own this?

Sure

**Comment by fiftyeightandeight** [comment]
@hecool108 @hyossid For price update, do we want to use [tradingview](https://www.tradingview.com/brokerage-integration/)?

**Comment by hecool108** [comment]
Yes, Tradingview is a good choice, Will take a look at what if there is a pure JSON API. UI/UX design has some style settings, hence I am balancing between:

- A styled chart closed to the design (If the Tradingview has a react component ) or 
- Using another [chart](https://formidable.com/open-source/victory/docs/) with Tradingview API as datasource

@hyossid if Sidney or James can do an open-oracle test app to input required data to contract, that will be great.

**Comment by fiftyeightandeight** [comment]
@hecool108 @hyossid can we close this given https://github.com/alexgo-io/alex-v1/blob/env-test/init-js-tool/oracles.js?
