### ISSUE TITLE
[DEV] YTP Validation

### ISSUE THREAD

**Issue by hyossid** [alexgo-io/alex-v1#94]

**Comment by hyossid** [comment]
@fiftyeightandeight On YTP, after creating a pool and when you want to add liquidity, the token value on get-token-given-position on yield token equation becomes zero. (when total supply >0)

Here is the command I used on console : 
//Create YTP
(contract-call? .yield-token-pool create-pool 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.token-ayusda 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.token-usda 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.pool-token-usda-ayusda u1000000000 u1000000000)

// Add liquidity 
(contract-call? .yield-token-pool add-to-position  'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.token-ayusda 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.token-usda 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.pool-token-usda-ayusda u1000000000)


when adding liquidity, you can find that the values for parameter of get-token-given-position on Yield token equation are following;
balance-x : u1000000000
balance-y : u1000000000
t : u100000000
total-supply : u199989982
dx : u1000000000



It is weird that dx-term + dy-term exactly matches with total-supply and makes token value to zero in get-token-given-position on yield token equation

**Comment by fiftyeightandeight** [comment]
Hi Sidney, I pushed the changes relating to #89, which should fix what you see too. Would you please review the changes I made and update the test?

From: Sidney ***@***.***>
Date: Monday, 16 August 2021 at 10:31 PM
To: alexgo-io/alex-v1 ***@***.***>
Cc: fiftyeightandeight ***@***.***>, Mention ***@***.***>
Subject: Re: [alexgo-io/alex-v1] [DEV] YTP Validation (#94)

@fiftyeightandeight<https://github.com/fiftyeightandeight> On YTP, after creating a pool and when you want to add liquidity, the token value on get-token-given-position on yield token equation becomes zero. (when total supply >0)

Here is the command I used on console :
//Create YTP
(contract-call? .yield-token-pool create-pool 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.token-ayusda 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.token-usda 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.pool-token-usda-ayusda u1000000000 u1000000000)

// Add liquidity
(contract-call? .yield-token-pool add-to-position 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.token-ayusda 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.token-usda 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.pool-token-usda-ayusda u1000000000)

when adding liquidity, you can find that the values for parameter of get-token-given-position on Yield token equation are following;
balance-x : u1000000000
balance-y : u1000000000
t : u100000000
total-supply : u199989982
dx : u1000000000

It is weird that dx-term + dy-term exactly matches with total-supply and makes token value to zero in get-token-given-position on yield token equation
